const coupons = [
  "SAVE10", "WELCOME20", "FREESHIP", "DISCOUNT25", "HOLIDAY30",
  "SUMMER21", "SPRING50", "WINTER10", "FALLSALE", "SAVE15", 
  "OFFER99", "BARGAIN25", "EXTRA30", "SHOPNOW50", "BESTBUY10",
  "DEAL100", "SUPER50", "FLASH20", "LIMITED25", "NEWYEAR50",
  "LUCKY25", "PROMO75", "BIGSALE10", "DISCOUNT40", "WEEKEND50",
  "FREEDOM10", "SHOPSMART25", "HOTDEAL20", "HAPPY50", "HOLIDAY100",
  "GIFT50", "COUPON20", "SALE99", "WONDER50", "AMAZING30",
  "LUCKYWIN10", "EXCLUSIVE50", "SUMMER100", "TOPDEAL25", "MEGA10",
  "MEGA50", "VALUE20", "GETMORE50", "HOLIDAYSALE", "FREESHIPPING",
  "EXTRA99", "DEAL50", "HOT100", "NEWOFFER10", "GIFT100",
  "BESTDEAL25", "SHOP10", "BONUS50", "SUPERDEAL20", "WINBIG50",
  "SPECIAL10", "LUCKY30", "TOPBUY50", "EXTRA10", "OFFER50",
  "SUPERB10", "NEWDEAL25", "PROMOTION50", "TOPSALE20", "MEGASALE50",
  "BESTPRICE10", "BIGOFFER25", "FLASHDEAL20", "LIMITED50", "NEWYEAR100",
  "HAPPYSAVE10", "PROMODEAL25", "BIGGER50", "DISCOUNT75", "SUMMERDEAL10",
  "HOTSALES50", "GREAT10", "AMAZE25", "EXTRA25", "SUPER50SALE",
  "WEEKLY20", "SALEOUT50", "LIMITED10", "HOLIDAYOFFER", "BIG100",
  "VALUE25", "GREATDEAL20", "SHOPANDSAVE", "SAVE50", "SPECIALOFFER",
  "EXTRAPROMO", "BIGWIN50", "LUCKYSALE10", "TOPDEAL50", "SHOPSMART10",
  "HOLIDAYBONUS", "WONDER100", "EXCLUSIVE25", "AMAZINGDEAL", "LUCKYDRAW50",
  "GETITNOW", "SUPER50OFFER", "BESTDEAL10", "EXTRAOFFER", "SUMMERSALE",
  "TOPSHOP25", "WINMORE10", "BIGBARGAIN", "DEALNOW50", "LIMITEDDEAL",
  "SPECIAL100", "TOPWIN25", "WONDERDEAL", "LUCKYSHOP", "PROMOTIONS",
  "AMAZING50", "SAVEANDSHOP", "SUPERLUCKY", "BESTOFFER", "TOPBARGAIN",
  "FLASHOFFER", "LIMITEDTIME", "GIFTANDSAVE", "HOLIDAYLUCK", "WINBIG10",
  "AMAZE100", "GREATBUY50", "SUPERCOUPON", "NEWLUCK50", "BIGBONUS",
  "HOLIDAYDEAL", "SHOPMORE50", "GREATVALUE", "SUPERBIG10", "TOPCOUPON",
  "AMAZINGSAVE", "SPECIALWIN", "HOLIDAYSHOP", "TOPVALUE50", "DEALNOW100",
  "SAVEANDWIN", "HOLIDAYLUCKY", "AMAZINGBONUS", "LUCKYHOLIDAY", "NEWYEARLUCK",
  "SUMMERSAVE10", "HAPPYHOLIDAY", "BIGVALUE10", "EXCLUSIVEDEAL", "TOPBONUS10",
  "FLASHWIN25", "HOLIDAYPROMO", "LIMITEDLUCK", "HAPPYWIN50", "SAVEHOLIDAY",
  "HOLIDAYWONDER", "EXTRASAVE10", "LUCKYBIG50", "SPECIALOFFER50", "NEWLUCK100",
  "HOLIDAYSALE10", "GREATLUCK50", "HAPPYSHOP50", "EXTRAWIN50", "BIGLUCK50",
  "LIMITEDVALUE", "NEWYEARLUCKY", "SUPERLUCK50", "HAPPYLUCK10", "LUCKYDEAL50",
  "TOPLUCK100", "HOLIDAYTOP10", "FLASHHOLIDAY", "LIMITEDLUCKY", "LUCKYHAPPY50",
  "HOLIDAYEXTRA", "SPECIALHOLIDAY", "EXTRAHOLIDAY", "WONDERLUCK50", "SAVEANDSHOP50",
  "BIGWONDER10", "TOPPROMO50", "AMAZINGWIN50", "HOLIDAYHAPPY10", "SPECIALSHOP50",
  "HAPPYHOLIDAY10", "TOPLUCKY50", "LUCKYVALUE50", "HOLIDAYAMAZE10", "EXTRADEAL50",
  "SAVEANDLUCK10", "BIGSHOP50", "NEWYEARLUCK50", "SPECIALVALUE10", "LUCKYWIN100",
  "TOPSHOP50", "LUCKYNEWYEAR", "BIGEXTRA50", "HAPPYDEAL50", "SAVEHOLIDAY50",
  "EXTRABUY50", "WONDERLUCKY10", "LIMITEDSAVE10", "TOPEXTRA50", "HOLIDAYLUCKY10",
  "BIGSAVE50", "SPECIALBUY10", "EXTRAAMAZE10", "WONDERBIG50", "NEWYEARSHOP10",
  "HAPPYSAVE50", "SAVEHOLIDAY10", "LIMITEDAMAZE50", "HOLIDAYDEAL50", "HAPPYVALUE10",
  "LUCKYBIG100", "SPECIALLUCK50", "NEWYEARHAPPY", "BIGLUCK100", "TOPVALUE10",
  "SAVEANDHOLIDAY", "HAPPYBIG10", "LUCKYNEWYEAR10", "SPECIALBIG50", "NEWLUCKY50",
  "HAPPYBIGLUCK", "HOLIDAYDEAL10", "SAVEAMAZE50", "LUCKYNEWYEAR50", "SPECIALNEW10",
  "HOLIDAYEXTRA50", "BIGHOLIDAY10", "LUCKYHAPPYHOLIDAY", "SPECIALVALUE50", "TOPLUCK50"
];

const usedCoupons = new Set();

export default (req, res) => {
  const availableCoupons = coupons.filter((code) => !usedCoupons.has(code));

  if (availableCoupons.length === 0) {
    res.status(404).json({ error: "No more coupon codes available" });
    return;
  }

  const coupon = availableCoupons[0];
  usedCoupons.add(coupon);

  res.status(200).json({ coupon_code: coupon });
};
